name: Upload Python Package

on:
  release:
    types: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: AppThreat/sast-scan-action@master
      with:
        type: "python"

    - uses: actions/upload-artifact@v1
      with:
        name: reports
        path: reports

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build

    - name: Build and publish to pypi
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m build
        twine upload dist/*
