name: Repository CI

on:
  schedule:
    - cron: "30 22 * * *"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  repo-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Run static code analysis
        run: |
          python -m pip install bandit
          bandit -r src/
      
      - name: Run package vulnerability scans
        run: |
          python -m pip install safety
          # Added ignore for numpy (BUG)
          safety check -r requirements.txt -i 44715 

      - name: Run tests
        run: |
          python -m pip install pytest
          python -m pip install -r requirements.txt
          pytest -vvv

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build
      - name: Build package
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m build